{
"states_save_words":"send,එවපන්,sa",

"link_words":"nanan,njsj,nanan,nNan",

"paid_numbers":"94777839446,94776734030,94771665143,94720319480",

"status_text": [
  "Boot status sinhala", 
  "sinhala wadan", 
  "yamaha 11 sri lanka", 
  "bmw s1000r sri lanka", 
  "bmw car sri lanka", 
  "whatsapp status sinhala", 
  "sinhala song", 
  "sinhala lyrics", 
  "english song", 
  "feeling sinhala", 
  "cevic car sri lanka", 
  "boot song", 
  "sinhala wadan", 
  "sinhala amma wadan", 
  "sinhala thaththa wadan", 
  "kdh sri lanka", 
  "bus sri lanka", 
  "bike sri lanka", 
  "sad sinhala", 
  "whatsapp status wadan", 
  "friendship sinhala", 
  "lyrics sinhala", 
  "vibes sinhala", 
  "sinhala cartoon", 
  "japan bike", 
  "english wadan", 
  "tamil wadan", 
  "girl dance sinhala", 
  "girl dance", 
  "bike rider sinhala", 
  "v8 sri lanka", 
  "boot wadan",  
  "tv serious", 
  "sigma mail sinhala", 
  "sigma mail", 
  "status views sinhala", 
  "feel__free__music", 
  "studio_voix", 
  "ashoka_r", 
  "misky_page", 
  "mellow__official", 
  "sindu", 
  "budu bana", 
  "chamara weerasinghe", 
  "damith asanka", 
  "hana sri lanka", 
  "hirustra", 
  "sinhala teledrama", 
  "hindi fiim", 
  "saiman", 
  "panda_statas", 
  "justasecond_army", 
  "tharuzz_official",
"Dance video sri lanka",
"Funny video",
"Motivation video",
"Motivation video sinhala",
"Love story",
"Rimix song",
"Drop music video",
"Slowed Reverb song",
"Dj song music",
"Mashup",
"Chill Remix bass",
"CM Beats"
],






"song_name": [
  "lelena",
  "oba ha ma",
  "madu mala lesa",
  "sandawathiye",
  "kanda surinduni",
  "galana ganga",
  "sansara seka",
  "ganga addara",
  "sudu menike",
  "sanda midulata",
  "oba magemai",
  "mata aloke genadevi",
  "hiru sandu hamuwe",
  "madu sandak",
  "nil mini pahana",
  "tharuka",
  "prarthana",
  "seethala diwi gamane",
  "athma liyanage",
  "sanda tharaka",
  "salalihini kovul",
  "me tharam siyumali",
  "adara mal pawane",
  "asa yanata",
  "mithu mithu",
  "peradiga sulanga",
  "sitha wage asuwanna",
  "ran malak lesa",
  "mal wage piyanani",
  "muthu kirilli",
  "aluth kalawak",
  "nil akuraka",
  "jeevithaye",
  "katagatha man",
  "naadagam geeya",
  "api pawena",
  "rawum kaluma",
  "adarei mage adarei",
  "hitha mithuru",
  "me loku loketa",
  "thawa therumak wela",
  "sandawathiye hiru",
  "mal pipe geetha",
  "sanda midulata me",
  "duwanna ma langama",
  "egoda ganga nala",
  "gana loku dedunna",
  "hurathal sanda",
  "katu akule adare",
  "aththamage mul",
  "pahe galu wena",
  "denethin obata",
  "me hada themala",
  "nil sala niwidu",
  "mal kalu sudu",
  "nimthera langa",
  "gamata watina",
  "obage prathama",
  "kalu galhene",
  "rahase asunu",
  "nil diya",
  "thaniwee nagena",
  "naada wanawana",
  "mathake sitina",
  "rantharu hira",
  "haara haara",
  "thaama sanasumak",
  "parisariye wela",
  "adare denehe",
  "mal dekak samine",
  "miringu ruwak",
  "muwa hina wetha",
  "gamane langama",
  "nimnawa ran akurak",
  "raja kumaraya",
  "prabuddha jeewana",
  "suba sanda rasa",
  "sandun wala",
  "sithuwam wage",
  "rawum gala",
  "sirasa wasanthaya",
  "giniwel mal",
  "marambari",
  "amanada wiyo",
  "nil nethu",
  "oba enna",
  "sudu hansini",
  "neela kadal",
  "araliya landata",
  "maga akurata",
  "adare ra",
  "meedum gasak",
  "sudu rosa mal",
  "sanda madu sandawatha",
  "ran malak lesa",
  "giman halena",
  "ukule thel",
  "sinhala ran gee",
  "minisa samaga",
  "susum pem gee",
  "nelum male pichcha",
  "ganga pahan",
  "roshan mal",
  "ran dedunu",
  "adare tharam",
  "paaya sanda",
  "his thaniwela",
  "sanda rathi",
  "nilwan muwa",
  "oba pihitaki",
  "hadawathata dam",
  "tharindu geethaya",
  "hadakari obata",
  "obage suwanda",
  "seetha diya dothak",
  "me nil wala",
  "adan ma obi",
  "sanda watena gaha",
  "surangana weema",
  "pethum salu",
  "mahanel mal",
  "obata waram dennam",
  "adaraya nirwana",
  "kandu dalena mal",
  "hiru hara sanda",
  "anatha adare",
  "muthu maala",
  "kadulla thaleta",
  "rosa male",
  "ethin ethata",
  "punchi raththaran",
  "santhana jeewithe",
  "giman hale mage",
  "aramuna oba",
  "thawa tharam adare",
  "tharu ma paya",
  "kandulu gangawe",
  "seethala pemwatha",
  "obe pemwatha",
  "susum pem mal",
  "pipunu sanda",
  "rahu bandi",
  "nimthera wagakeema",
  "raththaran gee",
  "gasak pihitayi",
  "ma pem sita",
  "adarei mathu",
  "man daruwo",
  "sanda wagane",
  "katu akule",
  "punchi adare",
  "nil sarasavi",
  "nim him aloke",
  "obe sanda wage",
  "mal warusa",
  "seethala ganga",
  "sanda himi pathula",
  "mawena jeewithe",
  "tharu aruna",
  "sudu nelum",
  "sinaha hadana",
  "hiru himi obai",
  "thani oba mage",
  "kirulaka asu",
  "pathuma suwanda",
  "asiri wanthaya",
  "neela akasha",
  "oba mage pethi",
  "oya as diwi",
  "handa pem raththarana",
  "hiru sulan thale",
  "seetha dewpath",
  "nirwana sanda",
  "himidiriye asu",
  "pata pata heena",
  "dethata lan wela",
  "premaye maha weli",
  "sarase kale",
  "man bawanthara",
  "nil diyawara mal",
  "punchi kumari",
  "his wada sandun",
  "sanda tharaka wage",
  "sanda paya wage",
  "welikadaya",
  "sithuwili asuwen",
  "nalawana sanda",
  "nil pahan landune",
  "gala mudune",
  "susum suwandata",
  "pem madu suwanda",
  "thun mansala",
  "adi re surangana",
  "seetha wana gee",
  "adaraneeya sandawa",
  "suranganavi obai",
  "hiru mathaka",
  "nalina mal",
  "kataragama natha",
  "pem wiyan wan",
  "aloke diyak wage",
  "roshan dedunu",
  "devram vee",
  "lenchin mal",
  "himawara sandali",
  "giman mawila",
  "kumari sanda",
  "piyapath sala",
  "ruwata rata",
  "madhu suwanda",
  "nil gala mal",
  "punchi kumariye",
  "rosa mal sita",
  "sithuwili thale",
  "gimhana samaye",
  "aramunu lesa",
  "rathu roshan",
  "his aloke",
  "minisa wena",
  "wanali mala",
  "mathake ran",
  "wassa adaren",
  "punchi rosa",
  "mana wagakannam",
  "hiru jeewithe",
  "amathaka nowunu",
  "kandulu dana",
  "muthu rosa",
  "oba mage welawa",
  "sanda hiru adare",
  "nimnathi neela",
  "himath sukume",
  "sara saara",
  "adare thanha",
  "nil pathuma",
  "mal sara handa",
  "hiru maduru",
  "sudu aththamma",
  "kavi adare",
  "rosa male thanthare",
  "adarei oba sanda",
  "kandak se mathaka",
  "pansale pihitak",
  "obai mage kandulu",
  "mal wage seetha",
  "sanda nimnathi",
  "sanda renu thale",
  "adare maga thura",
  "kiri ithirewa",
  "seetha langama",
  "nimala oba mage",
  "hiru sudu pahana",
  "araliya madhu",
  "sanda oba wage",
  "punchi mal wage",
  "adara suwandak",
  "aththe me wage",
  "punchi putha",
  "raththarane sanda",
  "neela nil diya",
  "wasanthaye pem",
  "giman mathu",
  "hiru naga mage",
  "adara nisalu mal",
  "ran tharu sindu",
  "mada wage wage",
  "kalu gala menike",
  "manamali mage",
  "punchi mal pihitak",
  "giman yaya",
  "his suwanda mage",
  "punchi mahaththaya",
  "sanda meda wage",
  "mathaka sanda wage",
  "nil hima pathule",
  "mal renu raththarane",
  "kandulu gala obai",
  "sirasa oba wage",
  "neela wage mage",
  "man banda sanda",
  "hiru ran wela",
  "jeewithe mage sindu",
  "nimthera kadulak",
  "kataragama deviyo",
  "punchi duwa mage",
  "mathaka renu mage",
  "adare pinibara",
  "rosa pichcha wage",
  "mal renu athare",
  "mathu nil pathule",
  "ma wage obai",
  "hiru mathaka suwanda",
  "gala yaya nimnathi",
  "adare susum wage",
  "punchi deviye mage",
  "wasanthaye mage wela",
  "mathaka nimnathi wage",
  "hiru sanda mathaka",
  "rosa nimnathi pahana",
  "kandulu sanda wage",
  "giman gala mage",
  "nil diya mal wage",
  "punchi manamali",
  "hiru jeewithe wage",
  "sanda wage suwanda",
  "adare nimnathi suwanda",
  "kataragama obe sanda",
  "mathaka jeewithe wage",
  "pansale nimnathi suwanda",
  "kalu gala adare",
  "adare hiru thale",
  "nimnathi gala mage",
  "punchi deviyo wage",
  "hiru nimnathi thale",
  "rosa gala adare",
  "adarei punchi mage",
  "mathaka gala suwanda",
  "hiru suwanda wage",
  "adare kandulu gala",
  "jeewithe sanda wage",
  "mathaka wage obai",
  "sanda gala mage",
  "nimthera suwanda mage",
  "rosa nimnathi wage",
  "kalu gala suwanda",
  "punchi wage hiru",
  "adare gala suwanda",
  "jeewithe nimthera wage",
  "punchi mathaka wage",
  "hiru sanda gala",
  "adare mage punchi",
  "giman suwanda wage",
  "sanda gala hiru",
  "adarei mathaka wage",
  "punchi nimnathi gala",
  "jeewithe renu wage",
  "rosa nimnathi thale",
  "adare nimnathi gala",
  "hiru gala adare",
  "punchi gala hiru",
  "rosa adare mathaka",
  "nimthera gala wage",
  "kalu gala mathaka",
  "adare gala nimnathi",
  "punchi suwanda gala",
  "mathaka gala thale",
  "rosa gala mathaka",
  "hiru adare gala",
  "jeewithe gala wage",
  "mathaka suwanda gala",
  "rosa suwanda wage",
  "adare mathaka gala",
  "giman gala suwanda",
  "sanda gala thale",
  "adarei gala suwanda",
  "jeewithe nimnathi gala",
  "punchi renu gala",
  "adare thale gala",
  "sanda thale wage",
  "nimthera mathaka gala",
  "rosa mathaka thale",
  "adarei suwanda thale",
  "jeewithe gala suwanda",
  "sanda suwanda wage",
  "adare gala wage",
  "punchi mathaka gala",
  "hiru mathaka gala",
  "adare suwanda wage",
  "jeewithe nimthera gala",
  "rosa thale gala",
  "adare gala wage",
  "sanda nimthera wage",
  "nimnathi suwanda gala",
  "punchi gala wage",
  "adarei thale wage",
  "jeewithe thale gala",
  "rosa gala wage",
  "adarei gala wage",
  "jeewithe gala wage",
  "kirula mal wage",
  "mada setha palu",
  "sanda men bala",
  "udu gaha yame",
  "ranpath reya",
  "seethala ru sanasuma",
  "ada giman hala",
  "ganga rawuma",
  "pem rasa thalunu",
  "mathakayen obe",
  "pawee ma wage",
  "wehi sanda wage",
  "adare mage punchi",
  "kandulu denaganna",
  "araliya landune",
  "me jeewithe mal",
  "hiru ge suwanda",
  "sanda wage pahan",
  "punsanda mage",
  "mal wehi se",
  "rosa gee",
  "me nil sarasavi",
  "ran mal mena",
  "thani ma ruwak",
  "susum adaren",
  "himidiriye mal",
  "seethala niwahana",
  "ma wage hitha",
  "nil diya mal",
  "athithaya mathakaye",
  "adarei mage pethi",
  "sanda pahan thale",
  "mal wage gala",
  "kataragama deviyo",
  "punchi tharuka",
  "araliya mal wala",
  "nil paththare",
  "tharu mal wage",
  "mata his athare",
  "pem suwanda gatha",
  "hiru sanda thale",
  "sinduna men oba",
  "kandukare obata",
  "sudu gala ma wage",
  "man bawa sanda",
  "nil diya mage",
  "punchi rosa gala",
  "adare nimthera wage",
  "me punchi mal",
  "mal wage seethala",
  "katu gathata mage",
  "athithaye sanda wage",
  "obata ada sandu",
  "jeewithe gala mage",
  "ran men pahana",
  "adare kumari",
  "hiru gala athare",
  "me jeewithe rosa",
  "nimala wela",
  "me wage mathaka",
  "ganga diyareli",
  "sindhu wagena mage",
  "adarei hiru athare",
  "sinduna ruwak",
  "me mal pahan",
  "hiru wage gala",
  "me gala men",
  "rosa midula mage",
  "athithaye nil wage",
  "punchi pahan diya",
  "hiru ruwak athare",
  "sindu wage gala",
  "susum athare mage",
  "araliya wala mage",
  "kandu midula",
  "me giman mathaka",
  "sara wanan obata",
  "nimnathi wagakeema",
  "ganga obai mage",
  "rosa niwahana",
  "tharu wage suwanda",
  "hiru niwahana mage",
  "nil suwanda oba",
  "mathakaye ganga",
  "punchi pahan wage",
  "nimala ru athare",
  "me jeewithe sanda",
  "me tharu gala",
  "mal wage susum",
  "hiru wage suwanda",
  "kataragama nil",
  "rosa gala athare",
  "kalu gala athare",
  "punchi mathaka suwanda",
  "athithaye suwanda",
  "mal wage suwanda",
  "ganga niwahana",
  "nil paththare suwanda",
  "seethala gala",
  "me wage nimthera",
  "mal midula",
  "obata sindu",
  "hiru suwanda gala",
  "punchi tharu wage",
  "rosa midula",
  "nimala suwanda",
  "mathaka jeewithe",
  "sindunu gala",
  "sithumina wage",
  "seethala piyawara",
  "ran ratta",
  "pansal dakina",
  "mathakaye adare",
  "hiru mal man",
  "kataragama nawathina",
  "wela apahu",
  "sanda kehel geema",
  "nil thilina",
  "mal danen",
  "adare surangana",
  "ganga sema",
  "hitha santhosaya",
  "adare rattharan",
  "tharuwan thale",
  "obata anuradha",
  "muthu ran pahana",
  "ran mal utthara",
  "siththara dheera",
  "diyawara mehe",
  "sinda mathaka",
  "pansal thalaka",
  "sudu neela dawasaka",
  "ganga wale",
  "nil sarasavi",
  "adare viththiya",
  "piyasoma geethaya",
  "makulu ran mehela",
  "narayan tharu",
  "mal puruduwe",
  "dawasaka machan",
  "arawe suwanda",
  "nikini asuru",
  "surangana bawa",
  "ekathuwela jeewitha",
  "malmaya thalethi",
  "jeewitha vediya",
  "ganitho sirimal",
  "mathaka tharakawita",
  "rawuma susum",
  "roshan deduna",
  "sadaham siriyen",
  "rattharan adare",
  "mawatha diya",
  "nilwan ada wage",
  "sithaka piyawara",
  "sihina ma wathe",
  "satha kumari",
  "vidya sita",
  "swarnawathi",
  "asritha wanthaya",
  "ganga mathaka",
  "hitha tharu dawasaka",
  "sirini nilmini",
  "kanthalu adara",
  "sundara rana",
  "sanda athare",
  "gala malaka",
  "ranweera",
  "mathakaye suman",
  "sudara jiwithe",
  "seetha apahu",
  "yathi sindu",
  "mal bawa",
  "ajith apahu",
  "gimhani ra",
  "ranrathraya",
  "suwandara viradevi",
  "gimhana ra yama",
  "dilip somapala",
  "wada apahu",
  "wediya halana",
  "pansale sundara",
  "jeewithaye sathuta",
  "duwana siththara",
  "swasthi adare",
  "gane hayata",
  "muthu sambhavana",
  "kandulu wedana",
  "wehesi surangana",
  "nadiwana polwaththa",
  "serama himida",
  "sudatha surangana",
  "gaman raththaran",
  "mata wishrama",
  "ran dathu surangana",
  "madurangiththaya",
  "bawa kalu",
  "adare apahu",
  "rahasin kanthawa",
  "hemanthaya",
  "wewa usas nethi",
  "raththarana muthu",
  "agni jwala",
  "kalumath sahena",
  "pradeep rajapakse",
  "surangani sambhavana",
  "siththara ada",
  "gini aththa",
  "sinhale pemi",
  "ran sadaha",
  "punchi surangana",
  "pansal vevi",
  "sudu sandu",
  "nadaya hadawatha",
  "kamini salalihini",
  "ganga samaga",
  "siththarala ada",
  "sihina manaka",
  "yuganthaya sindu",
  "tharuwath leda",
  "aadara midule",
  "pudumaya maga",
  "rajasiri",
  "kandu pahan diya",
  "siththara gama",
  "hamuwe wala",
  "hemanthaya adare",
  "poya dinaka",
  "pachcha dhara",
  "daha niyama",
  "senven me",
  "hiru niwahana",
  "muththuchandaya",
  "ganga wage athi",
  "me watha peththaka",
  "mal sadahana",
  "surathal rantharu",
  "adare wage aya",
  "nil gala matha",
  "paayalu ratha",
  "kamita gamana",
  "me sitha sangatha",
  "hitha nirwana",
  "gini kara ganne",
  "raththarane pahana",
  "rahasin puthu",
  "siththara ruwan",
  "pandura kavi",
  "jathi wale duwana",
  "pahana hawa",
  "sangitha geethaya",
  "deepa ratnaya",
  "adare saha jeewithe",
  "kalu kumari",
  "subhaya siththara",
  "gathya saha surangana",
  "tharuwal surathal",
  "sathuta wage",
  "surathal gatha",
  "wewa mal",
  "siththara thiyana",
  "aththadi gathikara",
  "prarthana jivithayen",
  "mal renu niwahanaya",
  "tharu pora ne",
  "jathaka rangana",
  "athithaye mal",
  "jeewithaye tharakaya",
  "mithurangini",
  "rahasin putha",
  "kalugala thun",
  "sitha wathura",
  "adare navodaya",
  "surangana pada",
  "muthu sandaka",
  "me hathara manaya",
  "diyasiri ranmal",
  "siththara chithi",
  "gala niwahana",
  "adare thuru deyi",
  "sugandhi athare",
  "siththara saha sada",
  "matara gama",
  "hemanthaya mahamaya",
  "kothththu randuna",
  "mal araliya",
  "siththara thalitha",
  "kavi katha",
  "geetha banadara",
  "hitha sirasa",
  "ithiri randum",
  "awa nawa",
  "aadara sirena",
  "rahasin putha",
  "ratna galiye",
  "muthu rahase",
  "mahamudra",
  "sundara hamuwe",
  "prashansa kalu",
  "sita rantharu",
  "siththara vihiduma",
  "viharaya paara",
  "adare samawenna",
  "kavi samithiya",
  "duwan siri",
  "sundara aagama",
  "rahasin ada",
  "punchi suranganaya",
  "geethaya samaga",
  "kavi pahe gama",
  "roshani kalu",
  "kalpana newehi",
  "mahamaya vibaga",
  "sanda midula",
  "me susumath kira",
  "araliya kunu",
  "anuradha renu",
  "geeya thuruli",
  "geetha anuradha",
  "sathuththama",
  "sitha thurula",
  "nihal suwan",
  "jeewithe rahase",
  "sudu muthu",
  "geetha aragana",
  "dewa paramitha",
  "kavi vila",
  "nilunethima",
  "ganga surangana",
  "adu thalathu",
  "siththara palama",
  "kirula mal pahan",
  "gaga tharu magula",
  "jeewithe rayi",
  "kavi jeewithe",
  "rattharane midula",
  "sundara welawatha",
  "me puthu sita",
  "anuradha nalage",
  "rahasin lagi",
  "jeewithayen pasuwa",
  "sita roshani",
  "sundara araliye",
  "kamina rasaya",
  "raththarane surangani",
  "ganga chiththara",
  "punchi seetha",
  "aththama seva",
  "wathura ra",
  "ranweera niwahana",
  "gana malaya",
  "surathal sunanda",
  "aththama magulaya"
  
  ]  





  
}
